services:
  - type: web
    name: Githunguri kitchen f4e dashboard
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt
    startCommand: "gunicorn --chdir src app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
